#ddev-generated
# Remove the line above if you don't want this file to be overwritten when you run
# ddev add-on get and ddev add-on remove.

services:
  zap:
    image: ghcr.io/zaproxy/zaproxy:stable
    container_name: ddev-${DDEV_SITENAME}-zap
    hostname: ${DDEV_SITENAME}-zap
    command: zap-webswing.sh
    user: zap
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}
    expose:
      - "8080"
      - "8090"
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=8080:8080,8090:8090
      - HTTPS_EXPOSE=8443:8080,8490:8090
    volumes:
      - ".:/mnt/ddev_config:ro"
      - "./zap/wrk:/zap/wrk:rw"
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:8080/zap/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s
